### ISSUE TITLE
Encoding issues installing from Github

### ISSUE THREAD

**Issue by DanSimonet** [emmamorgan-tufts/QualtricsTools#1]
Thank you for developing this amazing shiny tool.

I am trying to install the `QualtricsTools` package directly from GitHub using `devtools::install_github("ctesta01/QualtricsTools")`. 

I receive the following installation error which appears to arise due to a bracket.
```
* installing *source* package 'QualtricsTools' ...
** R
Error in parse(outFile) : 
  C:/Users/Simmy566/AppData/Local/Temp/RtmpGgPwoK/devtools1028180b623d/ctesta01-QualtricsTools-f6e2ad3/R/reorganizing_survey_da:1587:36: unexpected '{'
1586: 
1587:     if (!is.null(question_indices) {
                                         ^
ERROR: unable to collate and parse R files for package 'QualtricsTools'
```
I do not know if this is a reproducible error or if it is just me. If the latter, is there a way to bypass this issue?

**Comment by emmamorgan-tufts** [comment]
We've actually shifted over the repository for this project. Try running devtools::install_github("emmamorgan-tufts/QualtricsTools") and see if that works instead.

This is a work in progress, so please let me know how it works and if you find any other issues.

**Comment by DanSimonet** [comment]
Thank you! I was able to successfully run the package and shiny app using the `emmamorgan-tufts` rather than `ctesta01` user. I will be showcasing Qualtrics to our OIT department this week so I have been testing out all the R API bells and whistles. I will make sure to reference `QualtricsTools.`
